### PR TITLE
added segtracker to UAE's internal debugger

### PR DESCRIPTION
**Pull request by cnvogelg**
As discussed in #101 this pull request adds the segtracker feature to FS-UAE

### CODE REVIEW

**Comment by FrodeSolheim** [comment]
Merged now :)

I have made a couple of additional commits, one where I added WITH_SEGTRACKER (and configure argument) and fixed indentation in existing source files. The other commit moves the new headers into the uae subdirectory.

Please test that everything works as it should :)

**Comment by cnvogelg** [comment]
Just tested the integrated code. Works like a charm.
Thanks for merging upstream!

**Comment by emoon** [comment]
@cnvogelg Hi, I'm working on adding debugging support to fs-uae (some info over here) https://github.com/FrodeSolheim/fs-uae/issues/63 and this PR of yours adds some interesting stuff like loading debug info (which I will need as well)

So I'm wonder if it's ok to "piggy-back" on some of your code (exactly how it will work I'm not sure yet but esp the loading of debug info would be great to use as I would have to implement something fairly the same otherwise) 

Cheers!

**Comment by cnvogelg** [comment]
Hi @emoon! Feel free to use the code as you like and adjust it to your needs. That's what OSS is for :)

BTW: Great project you are working on... I am really looking forward to a first release.

**Comment by emoon** [comment]
Awesome! Thanks :)

**Pull request merged**
