### PR TITLE
Add Midi Support to FS-UAE using the PortMidi library.

### LINKED ISSUE #30: Add MIDI support in FS-UAE?
Several people have voiced interest in MIDI support in FS-UAE (http://eab.abime.net/showthread.php?t=68356). There's currently no plans for this, but you can subscribe to this issue if you want to help with it, should it be implemented in the future - or just to get notifications if anything exciting happens in this regard.

### PR DESCRIPTION
**Pull request by cnvogelg**
* supports macos, Linux, and Windows
* automatically gets activated on Amiga serial port with midi baudrate
* adds both midi in and out connections
* full midi command support including sysex
* allows to configure the in/out ports in config with:

    serial_port = midi:<out_port>[,<in_port]

tested on macos and Ubuntu 18.04. resolves #30

### CODE REVIEW

**Comment by FrodeSolheim** [comment]
Thanks, this looks good and is a great addition to FS-UAE, I will merge into master soon :)

**Comment by rofl0r** [comment]
wouldn't it be better to add this to winuae ? so other projects that sync winuae sources could profit from it as well.

**Comment by cnvogelg** [comment]
Hi @FrodeSolheim, great to hear that you like my contribution. I am really looking forward to have midi in the official fs-uae builds...

@rofl0r, winuae already has midi support for years now. Unfortunately, this midi module is using Windows midi calls directly and therefore not portable. That's the reason why I wrote a new, portable one for fs-uae

**Comment by rofl0r** [comment]
> Unfortunately, this midi module is using Windows midi calls directly and therefore not portable

aww, but maybe @tonioni would be interested in having a portable version regardless ?

**Comment by FrodeSolheim** [comment]
Thanks again, finally merged :) So it will be included in the upcoming develoment release. Will try with a WHDLoad Sierra game now, I assume that should work with munt/mt32emu :)

**Comment by FrodeSolheim** [comment]
Works :D

It took a little debugging to get started, mostly because PortMidi did not represent devices like I expected to. I brought up Munt on alsa port 128:0 on Linux, but I had to use config serial_port = midi:Standard to get output on correct port.

I had the following devices on my system (and no indication on what "Standard" is):

    MIDI: found devices: 3
    MIDI: 0: 'ALSA', 'Midi Through Port-0'       OUT  
    MIDI: 1: 'ALSA', 'Midi Through Port-0'  IN *     
    MIDI: 2: 'ALSA', 'Standard'       OUT *

Anyway, that's not really a problem with this implementation, just something that needs to be improved at bit w.r.t. user friendlyness. But could simply be documentation. Or possibly some GUI in the Launcher. But initially, just documenting how to find/select the right device (and serial port option string) should be good enough. And run some additional testing on macOS and Windows :)

**Comment by FrodeSolheim** [comment]
I also added some minor changes to the MIDI code, the may change was to make midi_open a function without arguments (for compatibility with other UAE code) and a couple of compatibility functions to allows this to compile with WinUAE code that has been pulled in in the meantime.

**Comment by cnvogelg** [comment]
finally :) glad to see the merge on master...
As I said feel free to adjust the code so it fits your needs...
And yes, configuration is a bit low-level, but does its job. Documentation will help others to use it.

**Comment by Newk77** [comment]
very cool!! going to try this with OctaMED as soon as i can get the new dev version working

**Comment by vaccinemedia** [comment]
@cnvogelg could you possibly post a video on how to get this working on OSX?
@Newk77 did you ever test this with OctaMED? I'm trying to get it working with OctaMED currently and struggling

**Comment by vaccinemedia** [comment]
Further to my previous comment, I have managed to boot a hard drive file containing OctaMED and have just successfully played an old Midi file from the 90s @Newk77 in case you have not tested it yet. Latancy seems OK in of itself but I'm yet to play both Amiga audio and Midi together in the same song to see if there are any latency issues. I'll post videos on YouTube at some point if I have any success. Great job @cnvogelg :)

**Comment by vaccinemedia** [comment]
Just confirming that there is noticeable latency when playing a test block in OctaMED @Newk77 and using two tracks, one with a hihat played on a drum machine and the other track playing a hihat sample.

**Pull request merged**
